#!/bin/bash
set -em
cd `dirname "$0"`/../app

mkdir -p /tmp/demodb
mongod --quiet --nojournal --smallfiles --port 3014 --dbpath /tmp/demodb >/tmp/demodb.log &
mongod=$!

sleep 0.2

function killKids {
    kill $mongod 2>/dev/null
}
trap "killKids" SIGCHLD
trap "killKids" 0

echo -e "open \n\nhttp://localhost:3030/EG/\n\n"
node ./server.js
