#!/bin/bash
set -em
cd `dirname "$0"`/..
dbdir=`pwd`/tmp/demodb
mkdir -p $dbdir
mongod --quiet --nojournal --smallfiles --port 3014 --dbpath $dbdir >/tmp/demodb.log &
mongod=$!

sleep 0.1

function killKids {
    kill $mongod 2>/dev/null
}
trap "killKids" SIGCHLD
trap "killKids" 0

mongo localhost:3014/demo
