#!/bin/bash
set -e

. `dirname "$0"`/environ.sh
init ${1-demo}

# export NODE_OPTIONS='--prof'
# send SIGUSR1 to debug


fuser -s "$MONGO_DIR/mongod.lock" || ./scripts/startdb.sh $branch
cd app
echo -e "starting ${branch}...\c"
exec node ../node_modules/koru/lib/koru.js "$@"
