#!/bin/bash
set -e

. `dirname "$0"`/../config/environ.sh

if [[ -e tmp/yarn.lock && -e node_modules ]] && ${NODE} -v | cat - yarn.lock | diff -q - tmp/yarn.lock >/dev/null;then
    echo 'node_modules okay'
else
    echo 'yarn install...'
    rm -rf node_modules
    mkdir -p tmp
    yarn
    ${NODE} -v | cat - yarn.lock >tmp/yarn.lock
fi

cd app
echo -e "starting ${branch}...\c"
exec ${NODE} --inspect --es_staging $KORU_MODULE/lib/koru.js "$@"
